version: '3.8'

services:
  app:
    build: .
    container_name: discoverybox-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "node", "backend/utils/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - discoverybox-network

  nginx:
    image: nginx:alpine
    container_name: discoverybox-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - discoverybox-network

  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: discoverybox-backup
    restart: unless-stopped
    volumes:
      - ./database:/app/database:ro
    environment:
      - BACKUP_SCHEDULE=0 2 * * *  # Daily at 2 AM
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - discoverybox-network

networks:
  discoverybox-network:
    driver: bridge

volumes:
  database:
  uploads: